### ISSUE TITLE
Problem on CentOS Stream 9 - OCRmyPDF succeeded with warning(s): sh: line 1: ocrmypdf: command not found,	

### ISSUE THREAD

**Issue by mrojrti** [R0Wi-DEV/workflow_ocr#203]
When I try to install ocrmypdf via dnf/yum the packet was not found on the repository even epel installed.

Tried via Snap and Pip but I get the same error above on Nextlocu log:
<img width="1352" alt="Screenshot 2023-05-16 at 22 09 30" src="https://github.com/R0Wi-DEV/workflow_ocr/assets/14860931/2f3433d9-3798-4db7-a5bc-80c858249d09">

Can you help me, please?

Thank you

**Comment by R0Wi** [comment]
Hi @mrojrti, I can't immediately tell you what's wrong but I'd suggest you try the following steps to get closer to a solution:

1. Login to your server with your regular user (or root) and check if  `ocrmypdf --help` produces any reasonable output. If not, it seems like the installation is somehow completely broken on your system.
2.  Since OCR jobs are executed asynchronously via NC cron: check the way your [Nextcloud cron](https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/background_jobs_configuration.html#cron-jobs) is executed. If it's triggered via system cron, check which user executes the `cron.php` script. If it's executed via Webcron or Ajax, the user will be the same one running your webserver (in that case, check who is executing `apache2` / `httpd`). If you identified the system user executing your NC cron, open a new shell for that user and try step 1 again (for example `sudo -u www-data bash` and then again `ocrmypdf --help`). If that works, everything should be fine. If not, the executing user of the NC cron doesn't have access to the `ocrmypdf` binary. Try to make it accessible globally on your system by putting the directory where the ocrmypdf binary resides into your PATH or try something else so that this user can properly execute the `ocrmypdf` command

Hope this helps!

**Comment by mrojrti** [comment]
Hi @R0Wi !

All right, I redo some tests and the user apache on terminal can't run the commando `ocrmypdf`, returns command not found.
When I tried the cron with root, I get this message on log: 
<img width="944" alt="Screenshot 2023-05-19 at 18 42 58" src="https://github.com/R0Wi-DEV/workflow_ocr/assets/14860931/efd1b077-84cf-4b1b-af5c-ea1a3533195a">

So I do: `crontab -u apache -e` and add: `*/1  *  *  *  * php -f /var/www/html/cron.php`
Now no errors on cron log:
<img width="488" alt="Screenshot 2023-05-19 at 18 45 16" src="https://github.com/R0Wi-DEV/workflow_ocr/assets/14860931/7fe485ec-65c7-444c-9eb0-2192458c5229">

When I run the sudo -u apache ocrmypdf the command returns ok (I change a security configuration on sudoers to get this work)
<img width="1661" alt="Screenshot 2023-05-19 at 18 46 35" src="https://github.com/R0Wi-DEV/workflow_ocr/assets/14860931/78c3d722-3172-41e2-a5d0-96be05849cdb">


But still not working on Nextcloud, command not found =(

<img width="1361" alt="Screenshot 2023-05-19 at 18 49 46" src="https://github.com/R0Wi-DEV/workflow_ocr/assets/14860931/cd61cd00-cfca-45f2-8c82-954159158249">

I managed to get the command work on apacher user, but I don't know how to proceed now, can you help?
Any idea?

Thank you so much.

**Comment by R0Wi** [comment]
That really sounds like a taff one :smile: 

To get closer to a solution I'd not work with the crontab but instead call `cron.php` directly, think it's better for debugging. So:
1. Make sure your NC cron [is configured to `cron`](https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/background_jobs_configuration.html#cron)
2. Make sure the `apache` crontab is the only one with something like `php -f /var/www/html/cron.php`, so that really nothing else executes the `cron.php`
3. Remove or comment out the crontab entry for apache for the time  debugging
4. Upload a new file which matches your OCR flow
5. Open a new console and change your user to  apache (`sudo -u apache bash`) then execute `php -f /var/www/html/cron.php`. 
6. Inspect the logs
7. Don't forget to uncomment the crontab after testing

It would also be interesting to know where exactly the `ocrmypdf` binary resides on your system, because it has to be somewhere, where not every user has access to or doesn't have this location in his PATH. With a user where the `ocrmypdf` command succeeds, execute `whereis ocrmypdf`. On my system I get something like:

```bash
docker@489f65697e04:/var/www/html$ whereis ocrmypdf
ocrmypdf: /usr/bin/ocrmypdf
``` 

So you see it's below `/usr/bin`, which is part of the system PATH variable. If that's not the case on your system, another approach would be to create a symlink under `/usr/bin` which points to `ocrmypdf` (something like `ln -s <your-path> /usr/bin/ocrmypdf`). This should make the command globally available.

Good luck!

**Comment by mrojrti** [comment]
Hi, @R0Wi 
I hope you're well.

Finally, it works!!!

1 - The cron config was ok.
2 - Yes, it was the only one
3 to 7 - On this test the problem continue.

Executing `whereis ocrmypd`f the result was the expected and I had the symbolic link to.

Resolution:
I put the crontab on the **root** user, but **with sudo -u to apache**, like this
`*/5  *  *  *  * sudo -u apache php -f /var/www/html/cron.php`

Now it's working like a charm.

Thank you so much for your attention!

**Comment by R0Wi** [comment]
Happy to hear things are working now. Sounds to me indeed like in some situations the `apache` users PATH isn't setup correctly. Good to know 👍

**Comment by mrojrti** [comment]
Yes, I forgot 1 step that I did
As **root** I ran `visudo` and add the path `/usr/local/bin` of `ocrmypdf` to `secure_path`.

<img width="725" alt="Screenshot 2023-05-21 at 08 24 12" src="https://github.com/R0Wi-DEV/workflow_ocr/assets/14860931/78d5a863-8f1a-40ce-98d9-501cddbe27dd">

Thank you!
