### ISSUE TITLE
Add nextcloud notification when finished

### ISSUE THREAD

**Issue by ostasevych** [R0Wi-DEV/workflow_ocr#217]
It is not possible to understand when the operation is finished and the new OCRed file appeared, apart of refreshing-refreshing-refreshing the page. Please, add the nextcloud wide notification which shows that the OCR is successfully or not successfully finished.

**Comment by R0Wi** [comment]
A new notification feature was implemented with app version `1.27.1` in https://github.com/R0Wi-DEV/workflow_ocr/pull/214. You can find additional information in the docs https://github.com/R0Wi-DEV/workflow_ocr#get-feedback-via-notifications.

Sending notifications if the OCR process was successful is currently not supported. In my opinion this wouldn't really make sense since it might add a lot of notifications to your queue. Most of the time you're only interested in a notification if anything went wrong, otherwise you could expect your file to be corecctly processed within the next minutes (depending on your cron settings regarding the cron interval).

Hope this helps!

**Comment by ostasevych** [comment]
> A new notification feature was implemented with app version `1.27.1` in #214. You can find additional information in the docs https://github.com/R0Wi-DEV/workflow_ocr#get-feedback-via-notifications.
> 
> Sending notifications if the OCR process was successful is currently not supported. In my opinion this wouldn't really make sense since it might add a lot of notifications to your queue. Most of the time you're only interested in a notification if anything went wrong, otherwise you could expect your file to be corecctly processed within the next minutes (depending on your cron settings regarding the cron interval).
> 
> Hope this helps!

Well. How it works in my case: I assign the tag ocr, waiting for 2 minutes, during which I am refreshing the page, and voila in 2-3 minutes the file appears, dependently of the size, mimetype whatever. 

The thing is that the web page will not refresh, so I may not see the results, so the indication that the process is finished is expected, especially if that process is done in background. Please, add this explicitly or make it configurable: how to get the notification (by email, notify via nextcloud...), what will trigger the notification (success, failure or both). This will make the UX much better.

**Comment by R0Wi** [comment]
I will leave this issue open as a feature request to make the notifications configurable via UI. I have to say that this has currently not the highest prio and we do not have the capacity to implement this in the near future. Any contribution will be welcome.
