### ISSUE TITLE
OCR workflow should maintain modification date of original file

### ISSUE THREAD

**Issue by ferdiga** [R0Wi-DEV/workflow_ocr#256]
**Describe the bug**

we plan to load historical pdf files into the database and want to make them searchable using OCR workflow, which changes the modification date of the file - hence the important historical context of the modification date is "lost", limiting the usability of this great feature.
 
The ocrmypdf maintainer confirms, that ocrmypdf must change the modification date to comply to the standard.

For the OCR workflow I see 2 options:

- optionally restore the original modification date after adding the OCR layer.
- add the original modification date to the file name. Options 
-- prepend  using a format which allows sorting of the files like "yyyymmdd"
-- append

I have created a little python script which prepends the original modification date to all pdf files if no date is found at the beginning of the file to overcome this situation, but want to clarify the situation before I proceed.

**System**

- App version: 1.29
- Nextcloud version: 29.0.3

**How to reproduce**

trigger the OCR Workflow

**Comment by ferdiga** [comment]
Additional remark:
I would go for
"restore the original modification date after adding the OCR layer."
because
- we need to sort files by name and by (original modification) date.

**Comment by R0Wi** [comment]
Hi @ferdiga, thanks for the comprehensive explanation of your use-case. I think you already described that changing a file (so adding the OCR layer) automatically changes the last modified date, which is the expected behaviour when touching a file on a system and writing new content to it. The app itself just utilizes the NC API to create a new file version [here](https://github.com/R0Wi-DEV/workflow_ocr/blob/d129a88b67b05dbf8e0bf05ee2d8d57fd8f32356/lib/Service/OcrService.php#L223). The used `file_put_contents` just writes the file to the disk and creates a new file version in Nextcloud without the option to change any file metadata (see [here](https://github.com/nextcloud/server/blob/f58a88b11c7fdadaa1296d7e26c70dbc99d80869/lib/private/Files/View.php#L622).

A possible way to implement this after the new file version has been written would be to use [`touch`](https://github.com/nextcloud/server/blob/f58a88b11c7fdadaa1296d7e26c70dbc99d80869/lib/private/Files/View.php#L507) with a second argument (the old timestamp). In the UI we'd need to have an additional parameter like "Maintain original modification date". If set to true, we'd need to store the original modification date before creating the new file version, and write it back after it has been created.

**Comment by ferdiga** [comment]
Hi, thanks for looking into this,
Option 2:  once the file has the new tag, it has also the new timestamp. IMHO not the way to go.

What I probably will do 
- mount the NC files with favfs2
write a (python) script 
- makes a copy for pdf files without text layer - will be processed by NC OCR Workflow
write a cleanup script (disable certain triggers of the OCR workflow to not trigger the Workflow again)
- if such a copy with text layer is found , read the modification date from the original - mv the copy to the original and touch -mt with the original file stamp

another script is necessary for digitaly signed files - print not copy to destroy the signature, because the original must be preserved (ocrmypdf will not touch it) , nevertheless we want to have a searchable version.
