### ISSUE TITLE
Feature request: run the OCR process on another server

### ISSUE THREAD

**Issue by ferdiga** [R0Wi-DEV/workflow_ocr#260]
**Describe the feature request**

some NC-Service Providers do not offer OCR - support, because of the system load during ocrmypdf execution.

would be great to implement a solution like for fulltextsearch running in a docker on another server.
As no os-access is granted by the Service Providers (understandable) it must be solved in the APP IMO

**System**

- App version: [VERSION]
- Nextcloud version: [VERSION]
- PHP version: [VERSION]
- Environment: [Docker/native Apache/native PHP FPM/...]
- `ocrmypdf` version: [VERSION] 

**How to reproduce**

**Screenshots**

**Server log**

Please paste relevant content of your [ `nextcloud.log`](https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/logging_configuration.html#logging) file here.  It might make sense to first decrease the [Loglevel](https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/logging_configuration.html#log-level). Also, since the OCR process runs asynchronously, run your [cron.php](https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/background_jobs_configuration.html#cron) before copying the logs here.

```
Paste relevant server log lines here. Make sure to trim sensitive information.
```

**Browser log**

If you're observing Browser errors, please paste your developer tools logs here. 

Help for Chrome: https://developer.chrome.com/docs/devtools/console/#view
Help for Firefox: https://firefox-source-docs.mozilla.org/devtools-user/browser_console/index.html

```
Paste your developer tools logs here. 
```

**Additional context**

**Comment by R0Wi** [comment]
There's already a discussion going on [here](https://github.com/R0Wi-DEV/workflow_ocr/discussions/51). The main problem is that the implementation of such a "ocrMyPdf service" requires quite a bit of work. Things like encrypted communication and authentication are necessary to realize this.

Because of the fact that we've only very limited dev capacity, unfortunately this is definitely nothing for the near future. Of course contribution is always welcome, so if there's anybody willing to participate - feel free :+1:
